[features]
seeds = false
skip-lint = false

[programs.devnet]
my_anchor_project = "J8T7Dg51zWifVfd4H4G61AaVtmW7GqegHx3h7a59hKSa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dpbmaverick98/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1" 